{{- /* Check if Gateway is enabled in values AND if the Cluster supports Gateway API v1 */ -}}
{{- if and .Values.gateway.enabled (.Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1") -}}
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: {{ .Release.Name }}-listeners
  namespace: {{ .Release.Namespace }}
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.parentRef.name }}
    namespace: {{ .Values.gateway.parentRef.namespace }}
  listeners:
  - name: {{ .Release.Name }}-https
    protocol: HTTPS
    port: 443
    hostname: {{ .Values.gateway.host }}
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: {{ .Values.gateway.tls.secretName }}
    allowedRoutes:
      namespaces:
        from: Same
{{- end }}
